name: toybox CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
jobs:
  MacOS-12:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: Setup
      run: brew install gnu-sed
    - name: Configure
      run: make macos_defconfig
    - name: Build
      run: make
    - name: Test
      run: VERBOSE=all make tests

    - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      with:
        name: toybox-darwin
        path: ./toybox

  Ubuntu-20_04:
    strategy:
      matrix:
        target:
        - toolchain: x86_64-linux-musl-
          arch: x86_64

        - toolchain: aarch64-linux-musleabi-
          arch: aarch64

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: Setup
      run: |
        sudo apt-get install build-essential
        curl -LO https://landley.net/toybox/downloads/binaries/toolchains/latest/${{ matrix.target.toolchain }}cross.tar.xz
        tar xvf ${{ matrix.target.toolchain }}cross.tar.xz
    - name: Configure
      run: |
        make defconfig
        sed -i -e 's/^# CONFIG_VI is not set$/CONFIG_VI=y/' -e 's/^# CONFIG_SH is not set$/CONFIG_SH=y/' .config

    - name: Build
      env:
        CROSS_COMPILE: ./${{ matrix.target.toolchain }}cross/bin/${{ matrix.target.toolchain }}
        LDFLAGS: --static
      run: make toybox

    - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      with:
        name: toybox-${{ matrix.target.arch }}
        path: ./toybox
